API_KEY: "f678c3bfccmsheefd8b211281aa6p1725e6jsn648075b51051"
API_URL: "https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com"
API_RAPID_HOST: "spoonacular-recipe-food-nutrition-v1.p.rapidapi.com"

TMDB_ENDPOINT: "https://api.themoviedb.org/3/movie"
TMDB_API_KEY: dccfb35f165439731d84606110a670db