API_KEY: "f678c3bfccmsheefd8b211281aa6p1725e6jsn648075b51051"
API_URL: "https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com"
API_RAPID_HOST: "spoonacular-recipe-food-nutrition-v1.p.rapidapi.com"